global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'big-society-programmers'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['localhost:7004',
                  'localhost:7120',
                  'localhost:7048']

  - job_name: 'prometheus'
    static_configs: